In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [4]:
import numpy as np

In [3]:
list1 = [1,2,3,4]

In [4]:
a = np.array(list1)

In [5]:
type(a)

numpy.ndarray

In [7]:
a.shape

(4,)

In [13]:
lists = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [14]:
b = np.array(lists)

In [15]:
type(b)

numpy.ndarray

In [16]:
b.shape

(4, 3)

In [17]:
b


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

NumPy Built-in methods

In [19]:
b.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
#3-d
b.reshape(1,2,6)

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]])

In [28]:
tpl1 = (1,2,3)

In [29]:
type(tpl1)

tuple

In [30]:
c = np.array(tpl1, dtype = 'i') 

In [31]:
type(c)

numpy.ndarray

In [32]:
c

array([1, 2, 3], dtype=int32)

In [33]:
np.array([11,22,33,44], dtype = complex)

array([11.+0.j, 22.+0.j, 33.+0.j, 44.+0.j])

In [35]:
arr1 = np.array([5,6,7,8], ndmin = 5)
print(arr1)

[[[[[5 6 7 8]]]]]


In [5]:
#Generating Techniques
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
np.arange(0,14,2)

array([ 0,  2,  4,  6,  8, 10, 12])

In [7]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

In [8]:
np.linspace(5, 50, 25)

array([ 5.   ,  6.875,  8.75 , 10.625, 12.5  , 14.375, 16.25 , 18.125,
       20.   , 21.875, 23.75 , 25.625, 27.5  , 29.375, 31.25 , 33.125,
       35.   , 36.875, 38.75 , 40.625, 42.5  , 44.375, 46.25 , 48.125,
       50.   ])

In [10]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [20]:
np.logspace(2.0, 3.0, num = 4, base = 2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [21]:
np.random.rand(3,4)

array([[0.67704326, 0.27251475, 0.55709316, 0.98993708],
       [0.57743354, 0.80253042, 0.94372172, 0.50279058],
       [0.45287138, 0.21331905, 0.49145344, 0.96695157]])

In [22]:
np.random.rand(2,3)

array([[0.22387309, 0.41475788, 0.7307907 ],
       [0.03689333, 0.72544826, 0.42829187]])

In [23]:
np.random.rand(2,12)

array([[0.87293355, 0.90958761, 0.516508  , 0.56039813, 0.30739053,
        0.23249867, 0.37784933, 0.16119995, 0.19536551, 0.02558596,
        0.36777042, 0.07589353],
       [0.25281257, 0.708518  , 0.44665515, 0.39205854, 0.73136866,
        0.23890506, 0.30755049, 0.4925726 , 0.05025515, 0.48171293,
        0.56492563, 0.97658663]])

In [24]:
np.random.rand(100)

array([0.50185794, 0.53381984, 0.99802789, 0.76376722, 0.8906275 ,
       0.19763513, 0.30869773, 0.52545524, 0.54098994, 0.3622838 ,
       0.42656501, 0.48223291, 0.8815451 , 0.47778337, 0.53208151,
       0.06427522, 0.18334498, 0.68590046, 0.29883031, 0.5179404 ,
       0.01556515, 0.58902015, 0.73600702, 0.80549173, 0.74665543,
       0.3445743 , 0.6785854 , 0.32159343, 0.56822045, 0.68306193,
       0.48081673, 0.67908163, 0.77556041, 0.97499213, 0.16747867,
       0.93698345, 0.92831564, 0.74307541, 0.98270661, 0.11908571,
       0.12197669, 0.34726341, 0.36326234, 0.92924881, 0.62404503,
       0.82308031, 0.74457636, 0.08845467, 0.21124049, 0.63242737,
       0.64337077, 0.29232048, 0.67882941, 0.87944303, 0.73988011,
       0.90707027, 0.69406109, 0.91937948, 0.07554057, 0.61064998,
       0.73061932, 0.08053544, 0.89690713, 0.12188055, 0.39198897,
       0.55399693, 0.55140255, 0.66725277, 0.06827832, 0.67225776,
       0.5148434 , 0.91311165, 0.47096308, 0.71304253, 0.45653

In [26]:
np.random.randint(100, size = 8)

array([61, 21, 99,  0, 33,  3, 50, 15])

In [27]:
np.random.randint(4,16, 8)

array([15,  8,  5,  7,  7, 10, 15, 15])

NumPy Built-in Functions

In [28]:
a = np.array([1,2,3,4])

In [29]:
np.min(a)

1

In [30]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [31]:
np.square(a)

array([ 1,  4,  9, 16])

In [33]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [34]:
np.mean(a)

2.5

Inexing