In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

In [3]:
list1 = [1,2,3,4]

In [4]:
a = np.array(list1)

In [5]:
type(a)

numpy.ndarray

In [7]:
a.shape

(4,)

In [13]:
lists = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [14]:
b = np.array(lists)

In [15]:
type(b)

numpy.ndarray

In [16]:
b.shape

(4, 3)

In [17]:
b


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

NumPy Built-in methods

In [19]:
b.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
#3-d
b.reshape(1,2,6)

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]])

In [28]:
tpl1 = (1,2,3)

In [29]:
type(tpl1)

tuple

In [30]:
c = np.array(tpl1, dtype = 'i') 

In [31]:
type(c)

numpy.ndarray

In [32]:
c

array([1, 2, 3], dtype=int32)

In [33]:
np.array([11,22,33,44], dtype = complex)

array([11.+0.j, 22.+0.j, 33.+0.j, 44.+0.j])

In [35]:
arr1 = np.array([5,6,7,8], ndmin = 5)
print(arr1)

[[[[[5 6 7 8]]]]]
